# Generated by Django 2.2.12 on 2022-04-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220410_0516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='listName',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='reviews',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.customers'),
            preserve_default=False,
        ),
    ]
