# Generated by Django 2.2.12 on 2022-04-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220416_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reviews',
        ),
    ]
