# Generated by Django 2.2.12 on 2022-04-16 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('rating', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customers')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.books_details')),
            ],
        ),
    ]
