# Generated by Django 2.2.12 on 2022-04-18 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books_tosell',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ebooks',
            name='id',
        ),
        migrations.AlterField(
            model_name='books_tosell',
            name='isbn',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='ebooks',
            name='isbn',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
